version: '3'

services:
  master:
    image: mariadb:10.1.25
    env_file:
      - ./.env.sample
    volumes:
      - ./configs/my.cfg:/etc/mysql/my.cnf
    command: ["mysqld", "--server-id=1", "--report-host=master"]

  slave:
    image: mariadb:10.3.15
    env_file:
      - ./.env.sample
    volumes:
      - ./configs/my.cfg:/etc/mysql/my.cnf
    command: ["mysqld", "--server-id=2", "--report-host=slave", "--read-only"]
    depends_on:
      - master

  manager:
    image: signal18/replication-manager:2.1
    volumes:
      - ./configs/config.toml:/etc/replication-manager/config.toml
    ports:
      - 127.0.0.1:10001:10001
    depends_on:
      - master
      - slave
